{
  "type": "record",
  "name": "EnrichedEarthquakeEvent",
  "namespace": "com.rhonnydc.seismic",
  "fields": [
    { "name": "event_id", "type": "string" },
    { "name": "source", "type": "string" },
    { "name": "source_event_id", "type": "string" },
    {
      "name": "event_time_utc",
      "type": "string",
      "doc": "ISO 8601 timestamp in UTC."
    },
    {
      "name": "updated_at_utc",
      "type": "string",
      "doc": "ISO 8601 timestamp in UTC."
    },
    { "name": "place", "type": "string" },
    { "name": "country", "type": "string" },
    { "name": "region", "type": "string" },
    { "name": "magnitude", "type": "double" },
    { "name": "magnitude_type", "type": ["null", "string"], "default": null },
    { "name": "depth_km", "type": "double" },
    { "name": "latitude", "type": "double" },
    { "name": "longitude", "type": "double" },
    { "name": "status", "type": "string" },
    { "name": "event_type", "type": "string" },
    { "name": "tsunami", "type": "boolean" },
    { "name": "url", "type": ["null", "string"], "default": null },
    {
      "name": "ingested_at",
      "type": "string",
      "doc": "ISO 8601 timestamp in UTC."
    },
    { "name": "severity_level", "type": "string" },
    { "name": "is_shallow", "type": "boolean" },
    { "name": "event_date_utc", "type": "string", "doc": "UTC date in YYYY-MM-DD format." },
    { "name": "event_hour_utc", "type": "int", "doc": "Hour of day in UTC, from 0 to 23." },
    {
      "name": "ingestion_latency_seconds",
      "type": "double",
      "doc": "Seconds between event_time_utc and ingested_at."
    },
    {
      "name": "processed_at_utc",
      "type": "string",
      "doc": "ISO 8601 timestamp in UTC."
    }
  ]
}
