{
  "type": "record",
  "name": "EnrichedEarthquakeEvent",
  "namespace": "com.rhonnydc.seismic",
  "fields": [
    {
      "name": "event_id",
      "type": "string"
    },
    {
      "name": "occurred_at",
      "type": "string"
    },
    {
      "name": "latitude",
      "type": "double"
    },
    {
      "name": "longitude",
      "type": "double"
    },
    {
      "name": "depth_km",
      "type": "double"
    },
    {
      "name": "magnitude",
      "type": "double"
    },
    {
      "name": "source",
      "type": "string"
    },
    {
      "name": "severity_level",
      "type": "string"
    },
    {
      "name": "processed_at",
      "type": "string"
    }
  ]
}
