{
  "type": "record",
  "name": "RawEarthquakeEvent",
  "namespace": "com.rhonnydc.seismic",
  "fields": [
    { "name": "event_id", "type": "string" },
    { "name": "source", "type": "string" },
    { "name": "source_event_id", "type": "string" },
    {
      "name": "event_time_utc",
      "type": "string",
      "doc": "ISO 8601 timestamp in UTC."
    },
    {
      "name": "updated_at_utc",
      "type": "string",
      "doc": "ISO 8601 timestamp in UTC."
    },
    { "name": "place", "type": "string" },
    { "name": "country", "type": "string" },
    { "name": "region", "type": "string" },
    { "name": "magnitude", "type": "double" },
    { "name": "magnitude_type", "type": ["null", "string"], "default": null },
    { "name": "depth_km", "type": "double" },
    { "name": "latitude", "type": "double" },
    { "name": "longitude", "type": "double" },
    { "name": "status", "type": "string" },
    { "name": "event_type", "type": "string" },
    { "name": "tsunami", "type": "boolean" },
    { "name": "url", "type": ["null", "string"], "default": null },
    {
      "name": "ingested_at",
      "type": "string",
      "doc": "ISO 8601 timestamp in UTC."
    }
  ]
}
