CREATE TABLE IF NOT EXISTS enriched_earthquake_events (
    event_id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    source_event_id TEXT NOT NULL,
    event_time_utc TIMESTAMPTZ NOT NULL,
    updated_at_utc TIMESTAMPTZ NOT NULL,
    place TEXT NOT NULL,
    country TEXT NOT NULL,
    region TEXT NOT NULL,
    magnitude DOUBLE PRECISION NOT NULL,
    magnitude_type TEXT,
    depth_km DOUBLE PRECISION NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL,
    event_type TEXT NOT NULL,
    tsunami BOOLEAN NOT NULL,
    url TEXT,
    ingested_at TIMESTAMPTZ NOT NULL,
    severity_level TEXT NOT NULL,
    is_shallow BOOLEAN NOT NULL,
    event_date_utc DATE NOT NULL,
    event_hour_utc INTEGER NOT NULL CHECK (event_hour_utc BETWEEN 0 AND 23),
    ingestion_latency_seconds DOUBLE PRECISION NOT NULL,
    processed_at_utc TIMESTAMPTZ NOT NULL,
    stored_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
